### PR TITLE
Fix invocation when plugin handle is -1

### PR DESCRIPTION
**Pull request by basilgello**
See comments in commit :)

### CODE REVIEW

**Comment by basilgello** [comment]
@petterreinholdtsen please check and merge this fix because the accompanying commits were merged in Yatse and pending in Kore. Thanks!

**Comment by petterreinholdtsen** [comment]
Looking at the patch, I realize that I do not understand the Kodi API enough to understand what is going on here.  Can you explain a bit more what this change is doing and how to reproduce the problem?

**Comment by basilgello** [comment]
Testing the related Yatse issue I noticed that invoking kodi-send CLI results in Kodi playing nothing. You are using Kodi from Debian so you can install `kodi-eventclients-kodi-send` package and try sending video to Invidious from terminal:

```shell
kodi-send --action=PlayMedia(plugin://plugin.video.invidious/?action=play_video&video_id=RYHrto5U5MY)
```

Trying to understand why I found out that `RunScript` flow deep inside Kodi invokes Python script with addon_id equal to -1 (which is passed to addon script on initialization and is later given as parameter to setResolvedUrl function). That renders the whole setResolvedUrl flow useless as Kodi can not distinguish which addon does the resolved media URL belong to. However, invoking PlayMedia from addon ditectly works even if addon_id bug is present in Kodi (albeit the URL in Yatse is shown as-is, not a fancy video clip title). This is better than previous behavior because the video is played in 100% invocations, and even tags for on-screen rich media display (duration, writers, author etc) are there.

**Comment by basilgello** [comment]
For upstream fix, we might need to do PR for Kodi master (Omega) and Nexus but first I'd like to check with teammates why -1 appears at all.

**Comment by petterreinholdtsen** [comment]
[Vasyl Gello]
> Testing the related Yatse issue I noticed that invoking kodi-send CLI
> results in Kodi playing nothing. You are using Kodi from Debian so you
> can install `kodi-eventclients-kodi-send` package and try sending
> video to Invidious from terminal:

I tried, but there is nothing listening on port 9777 on my LibreELEC
Kodi instance.  Not quite sure what I am doing wrong.  Wanted to test
this patch to see for my self that it make life easier.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by basilgello** [comment]
You need to enable the interface as described here: https://kodi.wiki/view/Settings/Services/Control

**Comment by petterreinholdtsen** [comment]
[Vasyl Gello]
> You need to enable the interface as described here:
> https://kodi.wiki/view/Settings/Services/Control

Thanks.  Then I did test the right thing.  Do not work, though.  Not
sure why.

Running

  strace strace kodi-send --host=192.168.169.170 --port=80  '--action=PlayMedia(plugin://plugin.video.invidious/?action=play_video&video_id=RYHrto5U5MY)'

End like this:

socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_IP) = 3
write(1, "Sending: {'type': 'action', 'con"..., 125Sending: {'type': 'action', 'content': 'PlayMedia(plugin://plugin.video.invidious/?action=play_video&video_id=RYHrto5U5MY)'}
) = 125
sendto(3, "XBMC\2\0\0\n\0\0\0\1\0\0\0\1\0T\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 116, 0, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("192.168.169.170")}, 16) = 116
getsockname(3, {sa_family=AF_INET, sin_port=htons(34862), sin_addr=inet_addr("0.0.0.0")}, [16]) = 0
getpeername(3, 0x7fff61e0e790, [16])    = -1 ENOTCONN (Transport endpoint is not connected)
close(3)                                = 0
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK, sa_restorer=0x7f607d8f5fd0}, {sa_handler=0x678c70, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK, sa_restorer=0x7f607d8f5fd0}, 8) = 0
munmap(0x7f607d047000, 135168)          = 0
munmap(0x7f607cec6000, 528384)          = 0
munmap(0x7f607dbde000, 16384)           = 0
exit_group(0)                           = ?
+++ exited with 0 +++

With netcat I am able to connect via TCP to the projector, and the web
page work, so the service se operational.

Anyway, not sure I will let my strange problems block progress, as the
change do not seem to break the functionally I am able to test, I'll
merge it.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by basilgello** [comment]
Thanks! :)

**Pull request merged**
